### ISSUE TITLE
Check types for `FinalDegreeOfFermentation` and `Carbonation`

### ISSUE THREAD

**Issue by tdankert** [Mindener-Landfrauen/Brauser.Common#23]
In FermentationAndMaturing.cs we have FinalDegreeOfFermentation and Carbonation. While implementing the converter it occured that these values are apparently are integer or double.
At this point, we do store these values as string and we should check for possible values.

@Johannes123123412341412412412412414 maybe you can give some insights here.

**Comment by Johannes123123412341412412412412414** [comment]
FinalDegreeOfFermentation is integer with unit %, Carbonation is double with unit g/l

**Comment by tdankert** [comment]
Alright. for FinalDegreeOfFermentation I would also choose a double. Except these percent values are always in an integer format?
